webtalk_init -webtalk_dir /home/pieter/Development/projects/FIDS/FASEC_prototype/FASEC_prototype.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 26 19:52:50 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "pqcpv1na13mfpim86c1n0p68sj" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1469552865000" -context "sdk\\\\application/1469552865000"
webtalk_add_data -client sdk -key hwid -value "1467273649000" -context "sdk\\\\application/1469552865000"
webtalk_add_data -client sdk -key bspid -value "1467274037000" -context "sdk\\\\application/1469552865000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1469552865000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1469552865000"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\application/1469552865000"
webtalk_add_data -client sdk -key uid -value "1469553758000" -context "sdk\\\\application/1469553758000"
webtalk_add_data -client sdk -key hwid -value "1467273649000" -context "sdk\\\\application/1469553758000"
webtalk_add_data -client sdk -key bspid -value "1467274037000" -context "sdk\\\\application/1469553758000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1469553758000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1469553758000"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1469553758000"
webtalk_add_data -client sdk -key uid -value "1469553848000" -context "sdk\\\\application/1469553848000"
webtalk_add_data -client sdk -key hwid -value "1467273649000" -context "sdk\\\\application/1469553848000"
webtalk_add_data -client sdk -key bspid -value "1467274037000" -context "sdk\\\\application/1469553848000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1469553848000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1469553848000"
webtalk_add_data -client sdk -key apptemplate -value "dhrystone" -context "sdk\\\\application/1469553848000"
webtalk_transmit -clientid 3658134109 -regid "" -xml /home/pieter/Development/projects/FIDS/FASEC_prototype/FASEC_prototype.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/pieter/Development/projects/FIDS/FASEC_prototype/FASEC_prototype.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/pieter/Development/projects/FIDS/FASEC_prototype/FASEC_prototype.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
