webtalk_init -webtalk_dir /home/pieter/Development/projects/FIDS/FASEC_prototype/FASEC_prototype.sdk2/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct 25 16:46:39 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b1h0dgvqc3f81dldd6cuhdjq6v" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1477405299000" -context "sdk\\\\bsp/1477405299000"
webtalk_add_data -client sdk -key hwid -value "1477065891000" -context "sdk\\\\bsp/1477405299000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1477405299000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1477405299000"
webtalk_add_data -client sdk -key uid -value "1477405494000" -context "sdk\\\\application/1477405494000"
webtalk_add_data -client sdk -key hwid -value "1477065891000" -context "sdk\\\\application/1477405494000"
webtalk_add_data -client sdk -key bspid -value "1477405299000" -context "sdk\\\\application/1477405494000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1477405494000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1477405494000"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1477405494000"
webtalk_transmit -clientid 1797177382 -regid "" -xml /home/pieter/Development/projects/FIDS/FASEC_prototype/FASEC_prototype.sdk2/webtalk/usage_statistics_ext_sdk.xml -html /home/pieter/Development/projects/FIDS/FASEC_prototype/FASEC_prototype.sdk2/webtalk/usage_statistics_ext_sdk.html -wdm /home/pieter/Development/projects/FIDS/FASEC_prototype/FASEC_prototype.sdk2/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
