# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_design/system_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design || ORIG_REF_NAME==system_design}]

# IP: bd/system_design/ip/system_design_processing_system7_0_0/system_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_design_processing_system7_0_0 || ORIG_REF_NAME==system_design_processing_system7_0_0}]

# XDC: bd/system_design/ip/system_design_processing_system7_0_0/system_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_design_processing_system7_0_0 || ORIG_REF_NAME==system_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/system_design/system_design_ooc.xdc
